# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Food Viewz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Food Viewz
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.11.0'
  target 'Food Viewz-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Food ViewzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Food Viewz-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Food Viewz-tvOS


end
